In [ ]:
import numpy as np

In [4]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [8]:
arr.reshape(3,1)
arr

array([1, 2, 3])

In [9]:
arr.mean()

np.float64(2.0)

In [10]:
arr.std()

np.float64(0.816496580927726)

In [13]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
reshaped = arr.reshape(5,1)
print("arr.reshape(5,1):\n", reshaped)


arr.reshape(5,1):
 [[1]
 [2]
 [3]
 [4]
 [5]]
